"""initial full schema

Revision ID: e7abdc3ae0f5
Revises: 
Create Date: 2026-09-04 12:43:39.736739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = 'e7abdc3ae0f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('document_sequences',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_parent_id'), ['parent_id'], unique=False)

    op.create_table('note_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('note_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_tags_id'), ['id'], unique=False)

    op.create_table('price_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_lists_id'), ['id'], unique=False)

    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_promotions_id'), ['id'], unique=False)

    op.create_table('sales_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('sales_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_channels_id'), ['id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_reorder_level', sa.Integer(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expiry_warning_days', sa.Integer(), nullable=False),
    sa.Column('low_stock_alerts', sa.Boolean(), nullable=False),
    sa.Column('expiry_alerts', sa.Boolean(), nullable=False),
    sa.Column('shipment_prefix', sa.String(length=20), nullable=False),
    sa.Column('work_order_prefix', sa.String(length=20), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=False),
    sa.Column('po_prefix', sa.String(length=20), nullable=False),
    sa.Column('receipt_prefix', sa.String(length=20), nullable=False),
    sa.Column('asn_prefix', sa.String(length=20), nullable=False),
    sa.Column('qc_prefix', sa.String(length=20), nullable=False),
    sa.Column('cc_prefix', sa.String(length=20), nullable=False),
    sa.Column('return_prefix', sa.String(length=20), nullable=False),
    sa.Column('transfer_prefix', sa.String(length=20), nullable=False),
    sa.Column('unallocated_prefix', sa.String(length=20), nullable=False),
    sa.Column('quarantine_prefix', sa.String(length=20), nullable=False),
    sa.Column('lpn_prefix', sa.String(length=20), nullable=False),
    sa.Column('lpn_move_prefix', sa.String(length=20), nullable=False),
    sa.Column('lpn_load_prefix', sa.String(length=20), nullable=False),
    sa.Column('lpn_unload_prefix', sa.String(length=20), nullable=False),
    sa.Column('stock_in_prefix', sa.String(length=20), nullable=False),
    sa.Column('stock_out_prefix', sa.String(length=20), nullable=False),
    sa.Column('adjustment_prefix', sa.String(length=20), nullable=False),
    sa.Column('require_qc_before_ship', sa.Boolean(), nullable=False),
    sa.Column('auto_allocate_stock', sa.Boolean(), nullable=False),
    sa.Column('enforce_fefo', sa.Boolean(), nullable=False),
    sa.Column('default_costing_method', sa.String(length=30), nullable=False),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('default_items_per_page', sa.Integer(), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=False),
    sa.Column('bank_details', sa.Text(), nullable=False),
    sa.Column('footer_note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_id'), ['id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=False),
    sa.Column('dashboard_widgets', sa.JSON(), nullable=True),
    sa.Column('last_login_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('asns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asn_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expected_arrival', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('received_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asns_asn_number'), ['asn_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_asns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asns_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asns_user_id'), ['user_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('doc_key', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_filename')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_doc', ['entity_type', 'entity_id', 'doc_key'], unique=False)
        batch_op.create_index('ix_attachments_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_id'), ['id'], unique=False)

    op.create_table('customer_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('customer_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_groups_price_list_id'), ['price_list_id'], unique=False)

    op.create_table('cycle_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cc_number', sa.String(length=50), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_counts_cc_number'), ['cc_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cycle_counts_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_counts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_counts_location_id'), ['location_id'], unique=False)

    op.create_table('lpns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lpn_number', sa.String(length=50), nullable=False),
    sa.Column('lpn_type', sa.String(length=20), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lpns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lpns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpns_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpns_lpn_number'), ['lpn_number'], unique=True)

    op.create_table('note_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('recurrence', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_templates_id'), ['id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('due_date', UTCDateTime(), nullable=True),
    sa.Column('recurrence', sa.String(length=10), nullable=False),
    sa.Column('recurrence_end', UTCDateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('is_serialized', sa.Boolean(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_receipt_number'), ['receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_receipts_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', UTCDateTime(), nullable=True),
    sa.Column('revoked_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('asn_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asn_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asn_id'], ['asns.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asn_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asn_items_asn_id'), ['asn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asn_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asn_items_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asn_items_product_id'), ['product_id'], unique=False)

    op.create_table('boms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_boms_product_id'), ['product_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['customer_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)

    op.create_table('cycle_count_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_count_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('counted_qty', sa.Integer(), nullable=True),
    sa.Column('variance', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_on_hand', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_count_id'], ['cycle_counts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_count_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_count_items_cycle_count_id'), ['cycle_count_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_count_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_count_items_product_id'), ['product_id'], unique=False)

    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), server_default=sa.text("(date('now'))"), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'lot_number', name='uq_lots_product_lot')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('note_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_label', sa.String(length=200), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_links_id'), ['id'], unique=False)

    op.create_table('note_tag_links',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['note_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)

    op.create_table('price_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_list_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_list_items_price_list_id'), ['price_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_list_items_product_id'), ['product_id'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_items_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_items_product_id'), ['product_id'], unique=False)

    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_items_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_items_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_items_receipt_id'), ['receipt_id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_provider', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_phone', sa.String(length=30), nullable=True),
    sa.Column('payment_provider_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('currency_symbol', sa.String(length=10), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_checkout_request_id', sa.String(length=64), nullable=True),
    sa.Column('refund_status', sa.String(length=20), nullable=True),
    sa.Column('refunded_at', UTCDateTime(), nullable=True),
    sa.Column('refund_method', sa.String(length=20), nullable=True),
    sa.Column('refund_provider', sa.String(length=20), nullable=True),
    sa.Column('refund_checkout_request_id', sa.String(length=64), nullable=True),
    sa.Column('promo_code', sa.String(length=50), nullable=True),
    sa.Column('promo_discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['sales_channels.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_user_id'), ['user_id'], unique=False)

    op.create_table('serial_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('lpn_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sold_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['lpn_id'], ['lpns.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'serial_number', name='uq_serial_numbers_product_serial')
    )
    with op.batch_alter_table('serial_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serial_numbers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_numbers_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_numbers_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_numbers_lpn_id'), ['lpn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serial_numbers_product_id'), ['product_id'], unique=False)

    op.create_table('stock_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('lpn_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['lpn_id'], ['lpns.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', 'lot_id', 'lpn_id', name='uq_stock_lines_loc_lot_lpn')
    )
    with op.batch_alter_table('stock_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_lines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_lines_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_lines_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_lines_lpn_id'), ['lpn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_lines_product_id'), ['product_id'], unique=False)
        batch_op.create_index('ix_stock_lines_product_lot', ['product_id', 'lot_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_number', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=True),
    sa.Column('wip_location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=True),
    sa.Column('completed_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wip_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_wip_location_id'), ['wip_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_wo_number'), ['wo_number'], unique=True)

    op.create_table('lot_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_lot_id', sa.Integer(), nullable=False),
    sa.Column('child_lot_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['parent_lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lot_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_links_child_lot_id'), ['child_lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_links_parent_lot_id'), ['parent_lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_links_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('quality_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qc_number', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('checked_by', sa.Integer(), nullable=False),
    sa.Column('checked_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_checks_checked_by'), ['checked_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_checks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_checks_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_checks_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_checks_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_checks_qc_number'), ['qc_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_quality_checks_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_items_sale_id'), ['sale_id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=False),
    sa.Column('tracking_number', sa.String(length=200), nullable=False),
    sa.Column('staging_location_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('ship_date', UTCDateTime(), nullable=True),
    sa.Column('shipped_at', UTCDateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['staging_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_sale_id'), ['sale_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipments_shipment_number'), ['shipment_number'], unique=True)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('serial_id', sa.Integer(), nullable=True),
    sa.Column('lpn_id', sa.Integer(), nullable=True),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['lpn_id'], ['lpns.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['serial_id'], ['serial_numbers.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_from_location_id'), ['from_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_lpn_id'), ['lpn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index('ix_stock_movements_reference', ['reference_type', 'reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_serial_id'), ['serial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_to_location_id'), ['to_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_transfer_id'), ['transfer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_user_id'), ['user_id'], unique=False)

    op.create_table('work_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.Column('quantity_issued', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_items_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_picked', sa.Integer(), nullable=False),
    sa.Column('quantity_packed', sa.Integer(), nullable=False),
    sa.Column('quantity_shipped', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_items_shipment_id'), ['shipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_items_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_items_id'))

    op.drop_table('shipment_items')
    with op.batch_alter_table('work_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_items_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_items_id'))

    op.drop_table('work_order_items')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_user_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_transfer_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_to_location_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_serial_id'))
        batch_op.drop_index('ix_stock_movements_reference')
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_lpn_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_lot_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_from_location_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_shipment_number'))
        batch_op.drop_index(batch_op.f('ix_shipments_sale_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_created_by'))
        batch_op.drop_index(batch_op.f('ix_shipments_created_at'))

    op.drop_table('shipments')
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_items_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_sale_items_id'))

    op.drop_table('sale_items')
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_checks_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_quality_checks_qc_number'))
        batch_op.drop_index(batch_op.f('ix_quality_checks_product_id'))
        batch_op.drop_index(batch_op.f('ix_quality_checks_lot_id'))
        batch_op.drop_index(batch_op.f('ix_quality_checks_location_id'))
        batch_op.drop_index(batch_op.f('ix_quality_checks_id'))
        batch_op.drop_index(batch_op.f('ix_quality_checks_checked_by'))

    op.drop_table('quality_checks')
    with op.batch_alter_table('lot_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_links_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_lot_links_parent_lot_id'))
        batch_op.drop_index(batch_op.f('ix_lot_links_id'))
        batch_op.drop_index(batch_op.f('ix_lot_links_child_lot_id'))

    op.drop_table('lot_links')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_wo_number'))
        batch_op.drop_index(batch_op.f('ix_work_orders_wip_location_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_product_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_created_by'))
        batch_op.drop_index(batch_op.f('ix_work_orders_bom_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('stock_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_lines_product_lot')
        batch_op.drop_index(batch_op.f('ix_stock_lines_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_lines_lpn_id'))
        batch_op.drop_index(batch_op.f('ix_stock_lines_lot_id'))
        batch_op.drop_index(batch_op.f('ix_stock_lines_location_id'))
        batch_op.drop_index(batch_op.f('ix_stock_lines_id'))

    op.drop_table('stock_lines')
    with op.batch_alter_table('serial_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serial_numbers_product_id'))
        batch_op.drop_index(batch_op.f('ix_serial_numbers_lpn_id'))
        batch_op.drop_index(batch_op.f('ix_serial_numbers_lot_id'))
        batch_op.drop_index(batch_op.f('ix_serial_numbers_location_id'))
        batch_op.drop_index(batch_op.f('ix_serial_numbers_id'))

    op.drop_table('serial_numbers')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_status'))
        batch_op.drop_index(batch_op.f('ix_sales_id'))
        batch_op.drop_index(batch_op.f('ix_sales_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_created_at'))
        batch_op.drop_index(batch_op.f('ix_sales_channel_id'))

    op.drop_table('sales')
    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_items_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_items_lot_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_items_location_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_items_id'))

    op.drop_table('receipt_items')
    with op.batch_alter_table('bom_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_bom_items_id'))
        batch_op.drop_index(batch_op.f('ix_bom_items_bom_id'))

    op.drop_table('bom_items')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_images_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_list_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_price_list_items_price_list_id'))
        batch_op.drop_index(batch_op.f('ix_price_list_items_id'))

    op.drop_table('price_list_items')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_id'))

    op.drop_table('order_items')
    op.drop_table('note_tag_links')
    with op.batch_alter_table('note_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_links_id'))

    op.drop_table('note_links')
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_lots_product_id'))
        batch_op.drop_index(batch_op.f('ix_lots_id'))
        batch_op.drop_index(batch_op.f('ix_lots_expiry_date'))

    op.drop_table('lots')
    with op.batch_alter_table('cycle_count_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_count_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_cycle_count_items_id'))
        batch_op.drop_index(batch_op.f('ix_cycle_count_items_cycle_count_id'))

    op.drop_table('cycle_count_items')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_group_id'))

    op.drop_table('customers')
    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boms_product_id'))
        batch_op.drop_index(batch_op.f('ix_boms_id'))

    op.drop_table('boms')
    with op.batch_alter_table('asn_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asn_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_asn_items_location_id'))
        batch_op.drop_index(batch_op.f('ix_asn_items_id'))
        batch_op.drop_index(batch_op.f('ix_asn_items_asn_id'))

    op.drop_table('asn_items')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_jti'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_receipts_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_parent_id'))
        batch_op.drop_index(batch_op.f('ix_products_location_id'))
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_products_created_at'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_id'))

    op.drop_table('notes')
    with op.batch_alter_table('note_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_templates_id'))

    op.drop_table('note_templates')
    with op.batch_alter_table('lpns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lpns_lpn_number'))
        batch_op.drop_index(batch_op.f('ix_lpns_location_id'))
        batch_op.drop_index(batch_op.f('ix_lpns_id'))

    op.drop_table('lpns')
    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_counts_location_id'))
        batch_op.drop_index(batch_op.f('ix_cycle_counts_id'))
        batch_op.drop_index(batch_op.f('ix_cycle_counts_created_by'))
        batch_op.drop_index(batch_op.f('ix_cycle_counts_cc_number'))

    op.drop_table('cycle_counts')
    with op.batch_alter_table('customer_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_groups_price_list_id'))
        batch_op.drop_index(batch_op.f('ix_customer_groups_id'))

    op.drop_table('customer_groups')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_id'))
        batch_op.drop_index('ix_attachments_entity')
        batch_op.drop_index('ix_attachments_doc')

    op.drop_table('attachments')
    with op.batch_alter_table('asns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asns_user_id'))
        batch_op.drop_index(batch_op.f('ix_asns_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_asns_id'))
        batch_op.drop_index(batch_op.f('ix_asns_asn_number'))

    op.drop_table('asns')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_id'))

    op.drop_table('settings')
    with op.batch_alter_table('sales_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_channels_id'))

    op.drop_table('sales_channels')
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotions_id'))
        batch_op.drop_index(batch_op.f('ix_promotions_code'))

    op.drop_table('promotions')
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_lists_id'))

    op.drop_table('price_lists')
    with op.batch_alter_table('note_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_tags_id'))

    op.drop_table('note_tags')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_parent_id'))
        batch_op.drop_index(batch_op.f('ix_locations_id'))
        batch_op.drop_index(batch_op.f('ix_locations_code'))

    op.drop_table('locations')
    op.drop_table('document_sequences')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
