const ALL_PERMISSIONS = [
  "dashboard.view",
  "products.view",
  "products.create",
  "products.update",
  "products.delete",
  "products.bulk",
  "products.import",
  "products.upload",
  "categories.view",
  "categories.create",
  "categories.update",
  "categories.delete",
  "customers.view",
  "customers.create",
  "customers.update",
  "customers.delete",
  "customers.import",
  "suppliers.view",
  "suppliers.create",
  "suppliers.update",
  "suppliers.delete",
  "suppliers.import",
  "stock.view",
  "stock.record",
  "stock.adjust",
  "stock.update",
  "stock.delete",
  "orders.view",
  "orders.create",
  "orders.update",
  "orders.delete",
  "sales.view",
  "sales.create",
  "sales.refund",
  "reports.view",
  "settings.view",
  "settings.update",
  "users.view",
  "users.create",
  "users.update",
  "users.delete",
  "activity.view",
  "notifications.view",
  "receipts.view",
  "receipts.create",
  "lots.view",
  "lots.update",
  "serial_numbers.view",
  "locations.view",
  "locations.create",
  "locations.update",
  "locations.delete",
  "asns.view",
  "asns.create",
  "asns.update",
  "asns.receive",
  "lpns.view",
  "lpns.create",
  "lpns.update",
  "lpns.delete",
  "cycle_counts.view",
  "cycle_counts.create",
  "cycle_counts.update",
  "cycle_counts.count",
];

const WORKER_PERMISSIONS = [
  "dashboard.view",
  "products.view",
  "categories.view",
  "customers.view",
  "suppliers.view",
  "stock.view",
  "orders.view",
  "orders.create",
  "orders.update",
  "sales.view",
  "sales.create",
  "reports.view",
  "settings.view",
  "activity.view",
  "notifications.view",
  "receipts.view",
  "lots.view",
  "serial_numbers.view",
  "locations.view",
  "asns.view",
  "lpns.view",
  "cycle_counts.view",
];

const ROLE_PERMISSIONS: Record<string, ReadonlySet<string>> = {
  admin: new Set(ALL_PERMISSIONS),
  worker: new Set(WORKER_PERMISSIONS),
};

export function can(role: string | undefined, permission: string): boolean {
  if (!role) return false;
  return ROLE_PERMISSIONS[role]?.has(permission) ?? false;
}
